version: 3

agent:
  authtoken: 2ZQ94aCuAnPVdrbPUd74FPobNPm_7kTc3zMQPwV32SdJvaCvz
  log_level: debug
  log: false

endpoints:
  - name: my-app-endpoint
    url: mullet-immortal-labrador.ngrok-free.app    
    upstream:
      url: frontend-angular:80
